### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by AnshumanPM** [luanon404/Selenium-On-Termux-Android#3]
Traceback (most recent call last):                  File "/data/data/com.termux/files/home/s.py", line 4, in <module>                                     driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^      File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__                        super().__init__(
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__                     super().__init__(
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__                       self.start_session(capabilities, browser_profile)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session                  response = self.execute(Command.NEW_SESSION, parameters)                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /data/data/com.termux/files/usr/lib/chromium/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by luanon404** [comment]
what option did u use?

**Comment by AnshumanPM** [comment]
https://github.com/luanon404/Selenium-On-Termux-Android#example-chrome-headless

**Comment by AnshumanPM** [comment]
https://github.com/luanon404/Selenium-On-Termux-Android#example-non-headless-chrome

**Comment by luanon404** [comment]
?

**Comment by luanon404** [comment]
![image](https://github.com/luanon404/Selenium-On-Termux-Android/assets/71830807/2a20146c-35d5-4d2a-8762-1faa55c8ef52)

**Comment by AnshumanPM** [comment]
2nd one

**Comment by luanon404** [comment]
which is your termux version?, did u follow my tutorial?

**Comment by AnshumanPM** [comment]
![Screenshot_20230607_160208](https://github.com/luanon404/Selenium-On-Termux-Android/assets/95046825/89d7ffbc-87c4-462b-b3b4-9f863d36a4de)
I have not clean download it. I already downloaded termux from fdroid so I skip 1st step

**Comment by luanon404** [comment]
then step? did u follow it?

**Comment by luanon404** [comment]
![image](https://github.com/luanon404/Selenium-On-Termux-Android/assets/71830807/f5e39cbb-9858-4ecd-84af-2cc763e2aa73)

**Comment by luanon404** [comment]
if u did all then add use this code for disable  devtools

**Comment by luanon404** [comment]
```
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--display=:1") # localhost:1 -> display ID = 1
driver = webdriver.Chrome(options=options)
driver.get("https://www.google.com")
driver.save_screenshot("/sdcard/download/screenshot.png")
driver.quit()
```
